apiVersion: podpools.dev/v1alpha1
kind: PodPool
metadata:
  labels:
    app.kubernetes.io/name: podpools
    app.kubernetes.io/managed-by: kustomize
  name: podpool-sample
spec:
  replicas: 5
  workloadTemplate:
    apiVersion: apps/v1
    kind: Deployment
    spec:
      template:
        spec:
          containers:
          - name: app
            image: nginx:latest
  groups:
  - name: base
    scaling:
      min: 3
    overrides:
      spec:
        template:
          spec:
            nodeSelector:
              node-type: on-demand
  - name: burst
    scaling:
      min: 0
      target: "70%"
    overrides:
      spec:
        template:
          spec:
            nodeSelector:
              node-type: spot
